### ISSUE TITLE
Peer Dependency error, failed install

### ISSUE THREAD

**Issue by rdemint** [strapi/starters-and-templates#12]
I believe the starter is installing the v3 template: https://github.com/strapi/strapi-template-corporate

Not the v4 template 'corporate' in this repo. 

My error is, 

```
C:\Users\raine\source\repos\nextStrapi2>npx create-strapi-starter qms-project next-corporate
? Choose your installation type Quickstart (recommended)
Installing @strapi/starter-next-corporate starter.
Creating a quickstart project.
Creating a new Strapi application at C:\Users\raine\source\repos\nextStrapi2\qms-project\backend.
Creating files.
Installing @strapi/template-corporate template.
Dependencies installed successfully.

Your application was created at C:\Users\raine\source\repos\nextStrapi2\qms-project\backend.

Available commands in your project:

  npm run develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  npm run start
  Start Strapi without watch mode.

  npm run build
  Build Strapi admin panel.

  npm run strapi
  Display all available commands.

You can start by doing:

  cd C:\Users\raine\source\repos\nextStrapi2\qms-project\backend
  npm run develop

Creating Strapi starter frontend at C:\Users\raine\source\repos\nextStrapi2\qms-project\frontend.
Installing frontend dependencies
- Installing dependencies:  See C:\Users\raine\AppData\Local\npm-cache\eresolve-report.txt for a full report. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-next-corporate@1.0.4
npm ERR! Found: next@11.0.1
npm ERR! node_modules/next
npm ERR!   next@"^11.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^8.1.1-canary.54 || ^9.0.0" from next-seo@4.7.1
npm ERR! node_modules/next-seo
npm ERR!   next-seo@"^4.7.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\raine\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\raine\AppData\Local\npm-cache\_logs\2022-02-03T01_46_05_091Z-debug.log
    at makeError (C:\Users\raine\AppData\Local\npm-cache\_npx\ecd569b0a81a6814\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\raine\AppData\Local\npm-cache\_npx\ecd569b0a81a6814\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installWithLogs (C:\Users\raine\AppData\Local\npm-cache\_npx\ecd569b0a81a6814\node_modules\create-strapi-starter\utils\build-starter.js:85:3)
    at async buildStarter (C:\Users\raine\AppData\Local\npm-cache\_npx\ecd569b0a81a6814\node_modules\create-strapi-starter\utils\build-starter.js:181:3)
| Installing dependencies:  npm ERR! A complete log of this run can be found in: npm ERR!     C:\Users\raine\AppData\Local\npm-cache\_logs\2022-02-03T01_46_05_091Z-debug.log
```

**Comment by rdemint** [comment]
I believe this is a known issue with npm vs. yarn. 
I used yarn and this is workable, although still errors in build. https://github.com/strapi/strapi/issues/11729
