### ISSUE TITLE
After install and run, frontend fails with Typeerror

### ISSUE THREAD

**Issue by keremkurtulus** [strapi/starters-and-templates#37]
Hey, I followed the steps in docs and installed everything successfully. After running both frontend and backend, the backend works correctly but the frontend throws a type error.
I did not do anything except installation steps in docs.

<img width="992" alt="Screen Shot 2022-04-17 at 14 06 23" src="https://user-images.githubusercontent.com/35422525/163712025-95bdacc4-8fb7-4f0b-8b53-1b3cd2564f19.png">

**Comment by VadimCiv** [comment]
I have the same issue

**Comment by VadimCiv** [comment]
fn getGlobalData response in frontend app
But if I try to make a request in (http://localhost:1337/graphql) It looks work

![Screen Shot 2022-04-19 at 4 31 49 PM](https://user-images.githubusercontent.com/87256872/164015507-3ee8bc9a-e088-4556-a599-5780725ff0f0.png)

LOG

globalRes Response {
[develop:frontend]   size: 0,
[develop:frontend]   timeout: 0,
[develop:frontend]   [Symbol(Body internals)]: {
[develop:frontend]     body: PassThrough {
[develop:frontend]       _readableState: [ReadableState],
[develop:frontend]       _events: [Object: null prototype],
[develop:frontend]       _eventsCount: 2,
[develop:frontend]       _maxListeners: undefined,
[develop:frontend]       _writableState: [WritableState],
[develop:frontend]       allowHalfOpen: true,
[develop:frontend]       [Symbol(kCapture)]: false,
[develop:frontend]       [Symbol(kCallback)]: null
[develop:frontend]     },
[develop:frontend]     disturbed: false,
[develop:frontend]     error: null
[develop:frontend]   },
[develop:frontend]   [Symbol(Response internals)]: {
[develop:frontend]     url: 'http://localhost:1337/graphql',
[develop:frontend]     status: 400,
[develop:frontend]     statusText: 'Bad Request',
[develop:frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] },
[develop:frontend]     counter: 0
[develop:frontend]   }
[develop:frontend] }
[develop:frontend] TypeError: Cannot read properties of undefined (reading 'global')
[develop:frontend]     at getGlobalData (webpack-internal:///./utils/api.js:362:22)
[develop:frontend]     at runMicrotasks (<anonymous>)
[develop:frontend]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[develop:frontend]     at async Function.MyApp.getInitialProps (webpack-internal:///./pages/_app.js:111:24)
[develop:frontend]     at async loadGetInitialProps (/Users/user/dev/civ-website/frontend/node_modules/next/dist/next-server/lib/utils.js:5:91)
[develop:frontend]     at async renderToHTML (/Users/user/dev/civ-website/frontend/node_modules/next/dist/next-server/server/render.js:27:1537)
[develop:frontend]     at async /Users/user/dev/civ-website/frontend/node_modules/next/dist/next-server/server/next-server.js:112:97
[develop:frontend]     at async __wrapper (/Users/user/dev/civ-website/frontend/node_modules/next/dist/lib/coalesced-function.js:1:330)
[develop:frontend]     at async DevServer.renderToHTMLWithComponents (/Users/user/dev/civ-website/frontend/node_modules/next/dist/next-server/server/next-server.js:137:387)
[develop:frontend]     at async DevServer.renderToHTML (/Users/user/dev/civ-website/frontend/node_modules/next/dist/next-server/server/next-server.js:138:1088)

**Comment by VadimCiv** [comment]
# Using Yarn - WORKING after installation!
yarn create strapi-starter my-site next-corporate

# Or using NPM - NOT WORKING
npx create-strapi-starter my-site next-corporate
