### ISSUE TITLE
Strapi Next Corporate Starter fail to install

### ISSUE THREAD

**Issue by maximelebreton** [strapi/starters-and-templates#48]
Hello,

I tried to install the [Strapi Next Corporate Starter](https://github.com/strapi/starters-and-templates/tree/main/packages/starters/next-corporate), but it fails to install...

I tried with Yarn and NPM, quickstart, and custom install, same problem.
I'm running on Windows 10, Node `16.15.1`, NPM `8.13.2`, Yarn `1.22.5`

```
Creating a quickstart project.
Creating a new Strapi application at C:\Users\****\Documents\backend.
Creating files.
Installing @strapi/template-corporate template.
Error: ⛔️ Template installation failed: Command failed: npm install @strapi/template-corporate@1.0.0 --no-save --silent


    at createProject (C:\Users\****\AppData\Local\Yarn\Data\global\node_modules\@strapi\generate-new\lib\create-project.js:82:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createQuickStartProject (C:\Users\****\AppData\Local\Yarn\Data\global\node_modules\@strapi\generate-new\lib\create-quickstart-project.js:23:3)
error Command failed.
Exit code: 1
```

Thanks for your help

**Comment by alatwagestream** [comment]
Has this been looked at all?  I'm getting the same!

**Comment by dziebold** [comment]
Same here

**Comment by ObayaDevOps** [comment]
Also facing this

**Comment by PhillipgDF** [comment]
Also having issues on corp starter...

**Comment by iconifyit** [comment]
I'm having the same issue with the Ecommerce starter.

**Comment by iconifyit** [comment]
After a little digging, it looks like the above starters are probably v3.x starters, which are deprecated. I found what I need here : https://github.com/strapi/starters-and-templates
