### ISSUE TITLE
Starter next-corporate with TypeScript: backend server not able to start due to TypeError

### ISSUE THREAD

**Issue by falk-miracode** [strapi/starters-and-templates#60]
# Description

Running the starter command ` yarn create strapi-starter my-site next-corporate` and picking the options "Custom" and "TypeScript", leads to `error: Cannot read properties of undefined (reading 'routes')`, so the backend server wasn't able to start.

"Quickstart" (JavaScript) does work.

# Steps to reproduce + outputs

* Use latest node 16 LTS
   ```
   ~/strapi-next-corporate-starter-test$ nvm use 16
   Now using node v16.17.0 (npm v8.15.0)
   ```
* Run Starter command
  * `> Custom (manual settings)`
  * `> TypeScript`
  * `> sqlite`
  ```
    ~/strapi-next-corporate-starter-test$ yarn create strapi-starter my-site next-corporate
    yarn create v1.22.15
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    success Installed "create-strapi-starter@4.3.6" with binaries:
          - create-strapi-starter
    ? Choose your installation type Custom (manual settings)
    Installing @strapi/starter-next-corporate starter.
    ? Choose your preferred language TypeScript
    ? Choose your default database client sqlite
    ? Filename: .tmp/data.db
    
    Creating a project with custom database options.
    Creating a new Strapi application at /home/falk/strapi-next-corporate-starter-test/my-site/backend.
    Creating files.
    Installing @strapi/template-corporate template.
    Dependencies installed successfully.
    
    Your application was created at /home/falk/strapi-next-corporate-starter-test/my-site/backend.
    
    Available commands in your project:
    
      yarn develop
      Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)
    
      yarn start
      Start Strapi without watch mode.
    
      yarn build
      Build Strapi admin panel.
    
      yarn strapi
      Display all available commands.
    
    You can start by doing:
    
      cd /home/falk/strapi-next-corporate-starter-test/my-site/backend
      yarn develop
    
    Creating Strapi starter frontend at /home/falk/strapi-next-corporate-starter-test/my-site/frontend.
    Installing frontend dependencies
    Dependencies installed successfully.
    Dependencies installed successfully.
    Starting the app
    yarn run v1.22.15
    $ cross-env FORCE_COLOR=1 npm-run-all -l -p develop:*
    $ wait-on http://localhost:1337/admin && yarn --cwd frontend develop
    $ yarn --cwd backend develop
    $ strapi develop
    [develop:backend ] Starting the compilation for TypeScript files in /home/falk/strapi-next-corporate-starter-test/my-site/backend
    [develop:backend ] Building your admin UI with development configuration...
    [develop:backend ] ℹ Compiling Webpack
    [develop:backend ] ✔ Webpack: Compiled successfully in 11.23s
    [develop:backend ] Admin UI built successfully
    [develop:backend ] [2022-08-31 11:27:38.773] debug: ⛔️ Server wasn't able to start properly.
    [develop:backend ] [2022-08-31 11:27:38.774] error: Cannot read properties of undefined (reading 'routes')
    [develop:backend ] TypeError: Cannot read properties of undefined (reading 'routes')
    [develop:backend ]     at Object.addCreateLocalizationAction (/home/falk/strapi-next-corporate-starter-test/my-site/backend/node_modules/@strapi/plugin-i18n/server/services/core-api.js:184:41)
    [develop:backend ]     at /home/falk/strapi-next-corporate-starter-test/my-site/backend/node_modules/@strapi/plugin-i18n/server/register.js:78:22
    [develop:backend ]     at Array.forEach (<anonymous>)
    [develop:backend ]     at extendLocalizedContentTypes (/home/falk/strapi-next-corporate-starter-test/my-site/backend/node_modules/@strapi/plugin-i18n/server/register.js:56:38)
    [develop:backend ]     at Object.module.exports [as register] (/home/falk/strapi-next-corporate-starter-test/my-site/backend/node_modules/@strapi/plugin-i18n/server/register.js:12:3)
    [develop:backend ]     at Object.register (/home/falk/strapi-next-corporate-starter-test/my-site/backend/node_modules/@strapi/strapi/lib/core/domain/module/index.js:47:46)
    [develop:backend ]     at Object.register (/home/falk/strapi-next-corporate-starter-test/my-site/backend/node_modules/@strapi/strapi/lib/core/registries/modules.js:33:19)
    [develop:backend ]     at async Strapi.runLifecyclesFunctions (/home/falk/strapi-next-corporate-starter-test/my-site/backend/node_modules/@strapi/strapi/lib/Strapi.js:510:5)
    [develop:backend ]     at async Strapi.register (/home/falk/strapi-next-corporate-starter-test/my-site/backend/node_modules/@strapi/strapi/lib/Strapi.js:379:5)
    [develop:backend ]     at async Strapi.load (/home/falk/strapi-next-corporate-starter-test/my-site/backend/node_modules/@strapi/strapi/lib/Strapi.js:456:5)
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    ERROR: "develop:backend" exited with 1.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
    Error: Command failed with exit code 1: yarn develop
        at makeError (/home/falk/.config/yarn/global/node_modules/execa/lib/error.js:60:11)
        at handlePromise (/home/falk/.config/yarn/global/node_modules/execa/index.js:118:26)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async buildStarter (/home/falk/.config/yarn/global/node_modules/create-strapi-starter/utils/build-starter.js:194:3)
    Done in 200.17s.
```

**Comment by Cally99** [comment]
Did you get a resolution to this? I'd like to use typescript and jsx if possible with the template

**Comment by webhype** [comment]
Looking for a solution / workaround as well.

**Comment by crdev** [comment]
Should the next-corporate template perhaps be removed? It's been non-functional for over a year now...
